language: node_js


node_js:
- "12"

before_install:
- npm ci
- npx version-from-git --travis

install:
- npm run prepublishOnly

before_deploy:
- npm pack
- git config --local user.name "CK Kashyap"
- git config --local user.email "ckkashyap@gmail.com"
- export TRAVIS_TAG=dev-streamingextensions
- git tag -f $TRAVIS_TAG
- cp dist/directline.js dist/directline-`cat package.json | jq -r .version`.js

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  body: "This build will be updated on every push. Please do not use it in production environment."
  file:
  - dist/directline*.js
  - botframework-directlinejs-*.tgz
  file_glob: true
  name: "Continuous integration build for Direct Line Streaming Extensions"
  on:
    branch: ckk/protocoljs
  overwrite: true
  prerelease: true
  skip_cleanup: true
