language: node_js

node_js:
- "12"

before_install:
- npm ci
- npx version-from-git --travis --template streamingextensions.short

install:
- npm run prepublishOnly

script:
- echo Tests disabled

before_deploy:
- npm pack
- git config --local user.name "William Wong"
- git config --local user.email "compulim@hotmail.com"
# - export TRAVIS_TAG=dev
# - git tag -f $TRAVIS_TAG
- mv dist/directline.js dist/directline-`cat package.json | jq -r .version`.js

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  body: "This build will be updated on every push. Please do not use it in production environment."
  file:
  - dist/directLine-*.js
  - botframework-directlinejs-*.tgz
  file_glob: true
  name: "Continuous integration build for Direct Line Streaming Extensions"
  on:
    branch: ckk/protocoljs
  overwrite: true
  prerelease: true
  skip_cleanup: true
